version: '3.4'

services:
  cardcost:
    image: ${DOCKER_REGISTRY-}cardcost
    build:
      context: .
      dockerfile: Cardcost/Dockerfile
  redis:
    container_name: redis
    hostname: redis
    image: sameersbn/redis:4.0.9-2    
    ports:
      - "6379:6379"
    expose:
      - "6379"
    